const { ATTR } = require("./types");

module.exports.RAID_MONSTERS = {
  브리가론: {
    type: [ATTR.GRASS, ATTR.FIGHT],
    skillType: [ATTR.LAND, ATTR.FIGHT, ATTR.ROCK, ATTR.GRASS],
    teraType: ATTR.ROCK,
  },
};

module.exports.USER_MONSTERS = {
  타부자고: {
    type: [ATTR.STEEL, ATTR.GHOST],
    safeType: [
      ATTR.STEEL,
      ATTR.DRAGON,
      ATTR.ROCK,
      ATTR.FLY,
      ATTR.ICE,
      ATTR.ESPER,
      ATTR.FAIRY,
      ATTR.GRASS,
      ATTR.BUG,
      ATTR.FIGHT,
      ATTR.NORMAL,
      ATTR.POISON,
    ],
    dangerType: [
      ATTR.GHOST,
      ATTR.LAND,
      ATTR.FIRE,
      ATTR.EVIL,
      ATTR.WATER,
      ATTR.THUNDER,
    ],
    tera: ATTR.GHOST,
    item: "조개껍질방울",
  },
  마릴리: {
    type: [ATTR.FAIRY, ATTR.WATER],
    safeType: [
      ATTR.FIGHT,
      ATTR.WATER,
      ATTR.BUG,
      ATTR.FIRE,
      ATTR.EVIL,
      ATTR.ICE,
      ATTR.DRAGON,
    ],
    dangerType: [
      ATTR.POISON,
      ATTR.THUNDER,
      ATTR.GRASS,
      ATTR.STEEL,
      ATTR.GHOST,
      ATTR.NORMAL,
      ATTR.LAND,
      ATTR.ROCK,
      ATTR.FLY,
      ATTR.ESPER,
      ATTR.FAIRY,
    ],
    tera: ATTR.EVIL,
    item: "조개껍질방울",
  },
  위유이: {
    type: [ATTR.EVIL, ATTR.FIRE],
    safeType: [
      ATTR.STEEL,
      ATTR.GHOST,
      ATTR.FIRE,
      ATTR.EVIL,
      ATTR.ICE,
      ATTR.GRASS,
      ATTR.ESPER,
    ],
    dangerType: [
      ATTR.FIGHT,
      ATTR.LAND,
      ATTR.WATER,
      ATTR.ROCK,
      ATTR.NORMAL,
      ATTR.POISON,
      ATTR.DRAGON,
      ATTR.BUG,
      ATTR.FLY,
      ATTR.THUNDER,
      ATTR.FAIRY,
    ],
    tera: ATTR.EVIL,
    item: "조개껍질방울",
  },
  무쇠손: {
    type: [ATTR.THUNDER, ATTR.FIGHT],
    safeType: [ATTR.STEEL, ATTR.ROCK, ATTR.BUG, ATTR.THUNDER, ATTR.EVIL],
    dangerType: [
      ATTR.LAND,
      ATTR.ESPER,
      ATTR.FAIRY,
      ATTR.FIGHT,
      ATTR.GHOST,
      ATTR.NORMAL,
      ATTR.POISON,
      ATTR.DRAGON,
      ATTR.WATER,
      ATTR.FIRE,
      ATTR.FLY,
      ATTR.ICE,
      ATTR.GRASS,
    ],
    tera: ATTR.FIGHT,
    item: "메트로놈",
  },
  미라이돈: {
    type: [ATTR.THUNDER],
    safeType: [ATTR.STEEL, ATTR.WATER, ATTR.FIRE, ATTR.FLY, ATTR.GRASS],
    dangerType: [
      ATTR.DRAGON,
      ATTR.LAND,
      ATTR.ICE,
      ATTR.FAIRY,
      ATTR.FIGHT,
      ATTR.GHOST,
      ATTR.NORMAL,
      ATTR.POISON,
      ATTR.ROCK,
      ATTR.BUG,
      ATTR.EVIL,
      ATTR.ESPER,
    ],
    tera: ATTR.THUNDER,
    item: "메트로놈",
  },
  // 라란티스: {
  //   type: [ATTR.GRASS],
  //   tera: ATTR.GRASS,
  //   item: "조개껍질방울",
  // },
};
