module.exports.ATTR = {
  NORMAL: "노말",
  FIRE: "불",
  WATER: "물",
  THUNDER: "번개",
  ICE: "얼음",
  GRASS: "풀",
  FIGHT: "격투",
  POISON: "독",
  LAND: "땅",
  FLY: "비행",
  BUG: "벌레",
  ESPER: "에스퍼",
  ROCK: "바위",
  GHOST: "고스트",
  DRAGON: "드래곤",
  EVIL: "악",
  STEEL: "강철",
  FAIRY: "페어리",
};

// [속성]: [[굉장함],[있음],[별로],[없음]]
module.exports.COMPATIBILITY = {
  [this.ATTR.NORMAL]: [
    [this.ATTR.FIGHT],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIRE,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.POISON,
      this.ATTR.LAND,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.ROCK,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [],
    [this.ATTR.GHOST],
  ],
  [this.ATTR.FIRE]: [
    [this.ATTR.WATER, this.ATTR.LAND, this.ATTR.ROCK],
    [
      this.ATTR.NORMAL,
      this.ATTR.THUNDER,
      this.ATTR.FIGHT,
      this.ATTR.POISON,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
    ],
    [
      this.ATTR.FIRE,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.BUG,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [],
  ],
  [this.ATTR.WATER]: [
    [this.ATTR.THUNDER, this.ATTR.GRASS],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIGHT,
      this.ATTR.POISON,
      this.ATTR.LAND,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.ROCK,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.FIRE, this.ATTR.WATER, this.ATTR.ICE, this.ATTR.STEEL],
    [],
  ],
  [this.ATTR.THUNDER]: [
    [this.ATTR.LAND],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIRE,
      this.ATTR.WATER,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.FIGHT,
      this.ATTR.POISON,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.ROCK,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.THUNDER, this.ATTR.FLY, this.ATTR.STEEL],
    [],
  ],
  [this.ATTR.GRASS]: [
    [
      this.ATTR.FIRE,
      this.ATTR.ICE,
      this.ATTR.POISON,
      this.ATTR.FLY,
      this.ATTR.BUG,
    ],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIGHT,
      this.ATTR.ESPER,
      this.ATTR.ROCK,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.WATER, this.ATTR.THUNDER, this.ATTR.GRASS, this.ATTR.LAND],
    [],
  ],
  [this.ATTR.ICE]: [
    [this.ATTR.FIRE, this.ATTR.FIGHT, this.ATTR.ROCK, this.ATTR.STEEL],
    [
      this.ATTR.NORMAL,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
      this.ATTR.GRASS,
      this.ATTR.POISON,
      this.ATTR.LAND,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.ICE],
    [],
  ],
  [this.ATTR.FIGHT]: [
    [this.ATTR.FLY, this.ATTR.ESPER, this.ATTR.FAIRY],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIRE,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.FIGHT,
      this.ATTR.POISON,
      this.ATTR.LAND,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.STEEL,
    ],
    [this.ATTR.BUG, this.ATTR.ROCK, this.ATTR.EVIL],
    [],
  ],
  [this.ATTR.POISON]: [
    [this.ATTR.LAND, this.ATTR.ESPER],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIRE,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
      this.ATTR.ICE,
      this.ATTR.FLY,
      this.ATTR.ROCK,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.STEEL,
    ],
    [
      this.ATTR.GRASS,
      this.ATTR.FIGHT,
      this.ATTR.POISON,
      this.ATTR.BUG,
      this.ATTR.FAIRY,
    ],
    [],
  ],
  [this.ATTR.LAND]: [
    [this.ATTR.WATER, this.ATTR.GRASS, this.ATTR.ICE],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIRE,
      this.ATTR.FIGHT,
      this.ATTR.LAND,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.POISON, this.ATTR.ROCK],
    [this.ATTR.THUNDER],
  ],
  [this.ATTR.FLY]: [
    [this.ATTR.THUNDER, this.ATTR.ICE, this.ATTR.ROCK],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIRE,
      this.ATTR.WATER,
      this.ATTR.POISON,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.GRASS, this.ATTR.FIGHT, this.ATTR.BUG],
    [this.ATTR.LAND],
  ],
  [this.ATTR.ESPER]: [
    [this.ATTR.BUG, this.ATTR.GHOST, this.ATTR.EVIL],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIRE,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.POISON,
      this.ATTR.LAND,
      this.ATTR.FLY,
      this.ATTR.ROCK,
      this.ATTR.DRAGON,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.FIGHT, this.ATTR.ESPER],
    [],
  ],
  [this.ATTR.BUG]: [
    [this.ATTR.FIRE, this.ATTR.FLY, this.ATTR.ROCK],
    [
      this.ATTR.NORMAL,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
      this.ATTR.ICE,
      this.ATTR.POISON,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.GRASS, this.ATTR.FIGHT, this.ATTR.LAND],
    [],
  ],
  [this.ATTR.ROCK]: [
    [
      this.ATTR.WATER,
      this.ATTR.GRASS,
      this.ATTR.FIGHT,
      this.ATTR.LAND,
      this.ATTR.STEEL,
    ],
    [
      this.ATTR.THUNDER,
      this.ATTR.ICE,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.ROCK,
      this.ATTR.GHOST,
      this.ATTR.DRAGON,
      this.ATTR.EVIL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.NORMAL, this.ATTR.FIRE, this.ATTR.POISON, this.ATTR.FLY],
    [],
  ],
  [this.ATTR.GHOST]: [
    [this.ATTR.GHOST, this.ATTR.EVIL],
    [
      this.ATTR.FIRE,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.LAND,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.ROCK,
      this.ATTR.DRAGON,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.POISON, this.ATTR.BUG],
    [this.ATTR.NORMAL, this.ATTR.FIGHT],
  ],
  [this.ATTR.DRAGON]: [
    [this.ATTR.ICE, this.ATTR.DRAGON, this.ATTR.FAIRY],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIGHT,
      this.ATTR.POISON,
      this.ATTR.LAND,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.ROCK,
      this.ATTR.GHOST,
      this.ATTR.EVIL,
      this.ATTR.STEEL,
    ],
    [this.ATTR.FIRE, this.ATTR.WATER, this.ATTR.THUNDER, this.ATTR.GRASS],
    [],
  ],
  [this.ATTR.EVIL]: [
    [this.ATTR.FIGHT, this.ATTR.BUG, this.ATTR.FAIRY],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIRE,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.POISON,
      this.ATTR.LAND,
      this.ATTR.FLY,
      this.ATTR.ROCK,
      this.ATTR.DRAGON,
      this.ATTR.STEEL,
    ],
    [this.ATTR.GHOST, this.ATTR.EVIL],
    [this.ATTR.ESPER],
  ],
  [this.ATTR.STEEL]: [
    [this.ATTR.FIRE, this.ATTR.FIGHT, this.ATTR.LAND],
    [this.ATTR.WATER, this.ATTR.THUNDER, this.ATTR.GHOST, this.ATTR.EVIL],
    [
      this.ATTR.NORMAL,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.ROCK,
      this.ATTR.DRAGON,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.POISON],
  ],
  [this.ATTR.FAIRY]: [
    [this.ATTR.POISON, this.ATTR.STEEL],
    [
      this.ATTR.NORMAL,
      this.ATTR.FIRE,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.LAND,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.ROCK,
      this.ATTR.GHOST,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.FIGHT, this.ATTR.BUG, this.ATTR.EVIL],
    [this.ATTR.DRAGON],
  ],
};
