module.exports.ATTR = {
  NORMAL: "노말",
  FIRE: "불",
  WATER: "물",
  THUNDER: "번개",
  ICE: "얼음",
  GRASS: "풀",
  FIGHT: "격투",
  POISON: "독",
  LAND: "땅",
  FLY: "비행",
  BUG: "벌레",
  ESPER: "에스퍼",
  ROCK: "바위",
  GHOST: "고스트",
  DRAGON: "드래곤",
  EVIL: "악",
  STEEL: "강철",
  FAIRY: "페어리",
};

// [속성]: [[굉장함],[있음],[없음]]
//         위에 없는 속성은 '있음' 속성
module.exports.COMPATIBILITY = {
  [this.ATTR.NORMAL]: [[this.ATTR.FIGHT], [], [this.ATTR.GHOST]],
  [this.ATTR.FIRE]: [
    [this.ATTR.WATER, this.ATTR.LAND, this.ATTR.ROCK],
    [
      this.ATTR.FIGHT,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.BUG,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [],
  ],
  [this.ATTR.WATER]: [
    [this.ATTR.THUNDER, this.ATTR.GRASS],
    [this.ATTR.FIRE, this.ATTR.WATER, this.ATTR.ICE, this.ATTR.STEEL],
    [],
  ],
  [this.ATTR.THUNDER]: [
    [this.ATTR.LAND],
    [this.ATTR.THUNDER, this.ATTR.FLY, this.ATTR.STEEL],
    [],
  ],
  [this.ATTR.GRASS]: [
    [
      this.ATTR.FIRE,
      this.ATTR.ICE,
      this.ATTR.POISON,
      this.ATTR.FLY,
      this.ATTR.BUG,
    ],
    [this.ATTR.WATER, this.ATTR.THUNDER, this.ATTR.GRASS, this.ATTR.LAND],
    [],
  ],
  [this.ATTR.ICE]: [
    [this.ATTR.FIRE, this.ATTR.FIGHT, this.ATTR.ROCK, this.ATTR.STEEL],
    [this.ATTR.ICE],
    [],
  ],
  [this.ATTR.FIGHT]: [
    [this.ATTR.FLY, this.ATTR.ESPER, this.ATTR.FAIRY],
    [this.ATTR.BUG, this.ATTR.ROCK, this.ATTR.EVIL],
    [],
  ],
  [this.ATTR.POISON]: [
    [this.ATTR.LAND, this.ATTR.ESPER],
    [
      this.ATTR.GRASS,
      this.ATTR.FIGHT,
      this.ATTR.POISON,
      this.ATTR.BUG,
      this.ATTR.FAIRY,
    ],
    [],
  ],
  [this.ATTR.LAND]: [
    [this.ATTR.WATER, this.ATTR.GRASS, this.ATTR.ICE],
    [this.ATTR.POISON, this.ATTR.ROCK],
    [this.ATTR.THUNDER],
  ],
  [this.ATTR.FLY]: [
    [this.ATTR.THUNDER, this.ATTR.ICE, this.ATTR.ROCK],
    [this.ATTR.GRASS, this.ATTR.FIGHT, this.ATTR.BUG],
    [this.ATTR.LAND],
  ],
  [this.ATTR.ESPER]: [
    [this.ATTR.BUG, this.ATTR.GHOST, this.ATTR.EVIL],
    [this.ATTR.FIGHT, this.ATTR.ESPER],
    [],
  ],
  [this.ATTR.BUG]: [
    [this.ATTR.FIRE, this.ATTR.FLY, this.ATTR.ROCK],
    [this.ATTR.GRASS, this.ATTR.FIGHT, this.ATTR.LAND],
    [],
  ],
  [this.ATTR.ROCK]: [
    [
      this.ATTR.WATER,
      this.ATTR.GRASS,
      this.ATTR.FIGHT,
      this.ATTR.LAND,
      this.ATTR.STEEL,
    ],
    [this.ATTR.NORMAL, this.ATTR.FIRE, this.ATTR.POISON, this.ATTR.FLY],
    [],
  ],
  [this.ATTR.GHOST]: [
    [this.ATTR.GHOST, this.ATTR.EVIL],
    [this.ATTR.POISON, this.ATTR.BUG],
    [this.ATTR.NORMAL, this.ATTR.FIGHT],
  ],
  [this.ATTR.DRAGON]: [
    [this.ATTR.ICE, this.ATTR.DRAGON, this.ATTR.FAIRY],
    [this.ATTR.FIRE, this.ATTR.WATER, this.ATTR.THUNDER, this.ATTR.GRASS],
    [],
  ],
  [this.ATTR.EVIL]: [
    [this.ATTR.FIGHT, this.ATTR.BUG, this.ATTR.FAIRY],
    [this.ATTR.GHOST, this.ATTR.EVIL],
    [this.ATTR.ESPER],
  ],
  [this.ATTR.STEEL]: [
    [this.ATTR.FIRE, this.ATTR.FIGHT, this.ATTR.LAND],
    [
      this.ATTR.NORMAL,
      this.ATTR.GRASS,
      this.ATTR.ICE,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.BUG,
      this.ATTR.ROCK,
      this.ATTR.DRAGON,
      this.ATTR.STEEL,
      this.ATTR.FAIRY,
    ],
    [this.ATTR.POISON],
  ],
  [this.ATTR.FAIRY]: [
    [this.ATTR.POISON, this.ATTR.STEEL],
    [this.ATTR.FIGHT, this.ATTR.BUG, this.ATTR.EVIL],
    [this.ATTR.DRAGON],
  ],
};

module.exports.RAID_MONSTERS = {
  브리가론: {
    type: [this.ATTR.GRASS, this.ATTR.FIGHT],
    skillType: [
      this.ATTR.LAND,
      this.ATTR.FIGHT,
      this.ATTR.ROCK,
      this.ATTR.GRASS,
    ],
    tera: this.ATTR.ROCK,
  },
};

module.exports.USER_MONSTERS = {
  타부자고: {
    type: [this.ATTR.STEEL, this.ATTR.GHOST],
    safeType: [
      this.ATTR.STEEL,
      this.ATTR.DRAGON,
      this.ATTR.ROCK,
      this.ATTR.FLY,
      this.ATTR.ICE,
      this.ATTR.ESPER,
      this.ATTR.FAIRY,
      this.ATTR.GRASS,
      this.ATTR.BUG,
      this.ATTR.FIGHT,
      this.ATTR.NORMAL,
      this.ATTR.POISON,
    ],
    dangerType: [
      this.ATTR.GHOST,
      this.ATTR.LAND,
      this.ATTR.FIRE,
      this.ATTR.EVIL,
      this.ATTR.WATER,
      this.ATTR.THUNDER,
    ],
    tera: this.ATTR.GHOST,
    item: "조개껍질방울",
  },
  마릴리: {
    type: [this.ATTR.FAIRY, this.ATTR.WATER],
    safeType: [
      this.ATTR.FIGHT,
      this.ATTR.WATER,
      this.ATTR.BUG,
      this.ATTR.FIRE,
      this.ATTR.EVIL,
      this.ATTR.ICE,
      this.ATTR.DRAGON,
    ],
    dangerType: [
      this.ATTR.POISON,
      this.ATTR.THUNDER,
      this.ATTR.GRASS,
      this.ATTR.STEEL,
      this.ATTR.GHOST,
      this.ATTR.NORMAL,
      this.ATTR.LAND,
      this.ATTR.ROCK,
      this.ATTR.FLY,
      this.ATTR.ESPER,
      this.ATTR.FAIRY,
    ],
    tera: this.ATTR.EVIL,
    item: "조개껍질방울",
  },
  위유이: {
    type: [this.ATTR.EVIL, this.ATTR.FIRE],
    safeType: [
      this.ATTR.STEEL,
      this.ATTR.GHOST,
      this.ATTR.FIRE,
      this.ATTR.EVIL,
      this.ATTR.ICE,
      this.ATTR.GRASS,
      this.ATTR.ESPER,
    ],
    dangerType: [
      this.ATTR.FIGHT,
      this.ATTR.LAND,
      this.ATTR.WATER,
      this.ATTR.ROCK,
      this.ATTR.NORMAL,
      this.ATTR.POISON,
      this.ATTR.DRAGON,
      this.ATTR.BUG,
      this.ATTR.FLY,
      this.ATTR.THUNDER,
      this.ATTR.FAIRY,
    ],
    tera: this.ATTR.EVIL,
    item: "조개껍질방울",
  },
  무쇠손: {
    type: [this.ATTR.THUNDER, this.ATTR.FIGHT],
    safeType: [
      this.ATTR.STEEL,
      this.ATTR.ROCK,
      this.ATTR.BUG,
      this.ATTR.THUNDER,
      this.ATTR.EVIL,
    ],
    dangerType: [
      this.ATTR.LAND,
      this.ATTR.ESPER,
      this.ATTR.FAIRY,
      this.ATTR.FIGHT,
      this.ATTR.GHOST,
      this.ATTR.NORMAL,
      this.ATTR.POISON,
      this.ATTR.DRAGON,
      this.ATTR.WATER,
      this.ATTR.FIRE,
      this.ATTR.FLY,
      this.ATTR.ICE,
      this.ATTR.GRASS,
    ],
    tera: this.ATTR.FIGHT,
    item: "메트로놈",
  },
  미라이돈: {
    type: [this.ATTR.THUNDER],
    safeType: [
      this.ATTR.STEEL,
      this.ATTR.WATER,
      this.ATTR.FIRE,
      this.ATTR.FLY,
      this.ATTR.GRASS,
    ],
    dangerType: [
      this.ATTR.DRAGON,
      this.ATTR.LAND,
      this.ATTR.ICE,
      this.ATTR.FAIRY,
      this.ATTR.FIGHT,
      this.ATTR.GHOST,
      this.ATTR.NORMAL,
      this.ATTR.POISON,
      this.ATTR.ROCK,
      this.ATTR.BUG,
      this.ATTR.EVIL,
      this.ATTR.ESPER,
    ],
    tera: this.ATTR.THUNDER,
    item: "메트로놈",
  },
  // 라란티스: {
  //   type: [this.ATTR.GRASS],
  //   tera: this.ATTR.GRASS,
  //   item: "조개껍질방울",
  // },
};
